name: YourBench CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      run: pip install uv
    
    - name: Create virtual environment
      run: uv venv
    
    - name: Install dependencies
      run: |
        . .venv/bin/activate
        uv pip install -e .
        uv pip install pytest pytest-cov
    
    - name: Run tests
      run: |
        . .venv/bin/activate
        python -m pytest tests/ --cov=yourbench --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
